config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "/#{I18n.locale}", controller: 'users', action: 'index'
  scope ':locale', locale: /ru|en/ do
    devise_for :users

    resources :clients, controller: :users, only: %i[index show] do
      resources :visits
    end

    resources :users, only: %i[destroy edit update]

    post '/search', to: 'search#search'
    get '/admin_index', to: 'visits#admin_index'
    get '/clients_list', to: 'users#clients'
    get '/team', to: 'users#team'
    put '/change_status', to: 'visits#change_status'
    get '/services', to: 'users#services'
    get '/portfolio', to: 'users#portfolio'
    get '*path', to: 'errors#error_404', via: :all
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def full_name
    "#{first_name} #{last_name}"
  end

  validate :first_name_cannot_be_blank, :last_name_cannot_be_blank, :phone_number_cannot_be_blank, :email_cannot_be_blank

  def first_name_cannot_be_blank
    errors.add(:first_name, "shouldn't be empty") if first_name.blank?
  end

  def last_name_cannot_be_blank
    errors.add(:last_name, "shouldn't be empty") if last_name.blank?
  end

  def phone_number_cannot_be_blank
    errors.add(:phone_number, "shouldn't be empty") if phone_number.blank?
  end

  def email_cannot_be_blank
    errors.add(:email, "shouldn't be empty") if email.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController  
  def index
    @user = current_user
    @users = User.all
  end

  def destroy
    @user = find_user
    return redirect_to :users unless @user

    if current_user.is_a?(Admin) || current_user == @user
      reset_session if current_user == @user
      @user.destroy
      redirect_to :user
    end
  end

  def edit
    @user = current_user
    redirect_to users_path unless @user == current_user || current_user.is_a?(Admin)
  end

  def update
    @user = find_user
    if @user.update user_params
      redirect_to :root
    else
      render :edit
    end
  end

  def team
    @masters = Master.all
  end

  def services
    @services = Service.all
  end

  def clients
    @clients = User.all
  end

  private

  def user_params
    @required_key = @user.is_a?(Admin) ? :admin : :client
    params.require(@required_key).permit(:first_name, :last_name, :email, :phone_number)
  end

  def find_user
    User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_records.html.erb
<div>
  <% @search_list.each do |record| %>  
    <% if record.class.name.equal? Service.name %>

      <p> <%= link_to record.service_name, services_path%> </p>

    <% elsif record.class.name.equal? Visit.name %>

      <p>Visit with <%= link_to record.service.service_name, client_visits_path(current_user) %> </p>

    <% end %>
  <% end %>
</div> 

app/views/users/clients.html.erb
<section id="why-us" class="why-us" style="margin-top: 150px">
	<div class="container">
		<div class="row">
			<%@clients.each do |client|%>
				<div class="col-lg-4">
					<div class="box" style="text-align: center">
						<span><%=client.first_name%> <%=client.last_name%></span>
							<p><%=client.email%></p>
						<span><%=client.phone_number%></span>
					</div>
				</div>
			<%end%>
		</div>
	</div>
</section>

app/views/users/edit.html.erb
<section id="visit" class="visit section-bg" style="margin-top: 150px">
  <div class="container">
    <div class="section-title">
      <h2>Edit Account</h2>
    </div>
    <div class="col-lg-12">
      <%= form_with url: user_path(id: @user.id), class: "php-email-form", model: @user do |form| %>
        <div class="row">
          <div class="col-md-6 form-group">
            <%= form.text_field :first_name, class: "form-control" %>
            <% @user.errors.full_messages_for(:first_name).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
          <div class="col-md-6 form-group">
            <%= form.text_field :last_name, class: "form-control" %>
            <% @user.errors.full_messages_for(:last_name).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 form-group">
            <%= form.email_field :email, class: 'form-control' %>   
            <% @user.errors.full_messages_for(:email).each do |message| %>
              <div><%= message %></div>
            <% end %> 
          </div>

          <div class="col-md-6 form-group">
            <%= form.text_field :phone_number, class: "form-control" %>
            <% @user.errors.full_messages_for(:phone_number).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
        </div>
        
        <div class="my-3">
          <div class="loading">Loading</div>
          <div class="error-message"></div>
          <div class="sent-message">Your message has been sent. Thank you!</div>
        </div>
        <div class="text-center"><button type="submit">Edit</button></div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 pt-2 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h1><%= t 'index.the_best_in_each_of_you' %></h1>
          <ul>
            <li><i class="ri-check-line"></i><%= t 'index.the_best_hairdressers'%></li>
            <li><i class="ri-check-line"></i><%= t 'index.quality_and_service'%></li>
            <li><i class="ri-check-line"></i><%= t 'index.price_and_your_time'%></li>
          </ul>
          <%if current_user%>
            <div class="mt-3">
              <%unless current_user.is_a?(Admin)%>
                <span class="btn-get-started scrollto"><%= link_to t("index.add_visit"), new_client_visit_path(current_user), method: :get, class: 'text-white' %></span>
              <%end%>
              <%if current_user.is_a?(Admin)%>
                <span class="btn-get-started scrollto"><%= link_to t("index.all_visits"), admin_index_path(), method: :get, class: 'text-white'%></span>
              <%else%>
                <span class="btn-get-started scrollto"><%= link_to t("index.my_visits"), client_visits_path(current_user), method: :get, class: 'text-white' %></span>
              <%end%>
            </div>
          <%end%>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img">
          <img src="assets/theme/img/hero-img.jpg" class="img-fluid" alt="">
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">
  
    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq">
      <div class="container">

        <div class="section-title">
          <h2><%= t 'index.frequently_asked_questions'%></h2>
        </div>

        <ul class="faq-list">

          <li>
            <div data-bs-toggle="collapse" class="collapsed question" href="#faq1"><%= t 'index.first_question'%> <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
            <div id="faq1" class="collapse" data-bs-parent=".faq-list">
              <p><%= t 'index.first_answer'%></p>
            </div>
          </li>

          <li>
            <div data-bs-toggle="collapse" href="#faq2" class="collapsed question"><%= t 'index.second_question'%><i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
            <div id="faq2" class="collapse" data-bs-parent=".faq-list">
              <p><%= t 'index.second_answer'%>             
              </p>
            </div>
          </li>

          <li>
            <div data-bs-toggle="collapse" href="#faq3" class="collapsed question"><%= t 'index.third_question'%> <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
            <div id="faq3" class="collapse" data-bs-parent=".faq-list">
              <p><%= t 'index.third_answer'%></p>
            </div>
          </li>

          <li>
            <div data-bs-toggle="collapse" href="#faq4" class="collapsed question"><%= t 'index.fourth_question'%><i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
            <div id="faq4" class="collapse" data-bs-parent=".faq-list">
              <p><%= t 'index.fourth_answer'%></p>
            </div>
          </li>
        </ul>

      </div>
    </section><!-- End Frequently Asked Questions Section -->

  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Template Main JS File -->
  <script src="assets/theme/js/main.js"></script>

app/views/users/portfolio.html.erb
<section id="portfolio" class="portfolio" style="margin-top: 50px">
    <div class="container">
    <div class="row portfolio-container">

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/10.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Coloring</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/10.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 1"><i class="bx bx-plus"></i></a>
                
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/5.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Hairstyle</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/5.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 3"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/3.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Haircut</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/3.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 2"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/4.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Children Haircut</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/4.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Card 2"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/2.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Men Haircut</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/2.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 2"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-app">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/6.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Children Haircut</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/6.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="App 3"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/7.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Hairstyle</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/7.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Card 1"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/8.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Hairstyle and Coloring</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/8.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Card 3"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>

        <div class="col-lg-4 col-md-6 portfolio-item filter-web">
        <div class="portfolio-wrap">
            <img src="/assets/theme/img/portfolio/1.jpg" class="img-fluid" alt="">
            <div class="portfolio-info">
            <h4>Lamination</h4>
            <div class="portfolio-links">
                <a href="/assets/theme/img/portfolio/1.jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="Web 3"><i class="bx bx-plus"></i></a>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</section>

app/views/users/services.html.erb
<!-- ======= Services Section ======= -->
<section id="services" class="services" style="margin-top: 50px">
  <div class="container">
    <div class="section-title">
      <h2><%= t 'services_page.services'%></h2>
      <p><%= t 'services_page.p_under_services'%></p>
    </div>
  </div>
</section><!-- End Services Section -->

<!-- ======= Features Section ======= -->
<section id="features" class="features">
  <div class="container">
    <div class="row">
      <% @services.each do |service|%>
        <div class="col-lg-3 col-md-4">
          <div class="icon-box">
            <h3><a href=""><i class="ri-check-line" style="color: #e80368;"></i><%= service.service_name%></a></h3>
          </div>
        </div>
      <%end%>
    </div>

  </div>
</section>

<section id="counts" class="counts section-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="count-box">
          <i class="bi bi-emoji-smile"></i>
          <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
          <p><%= t 'services_page.happy_clients'%></p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mt-5 mt-md-0">
        <div class="count-box">
          <i class="bi bi-journal-richtext"></i>
          <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
          <p><%= t 'services_page.great_service'%></p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
        <div class="count-box">
          <i class="bi bi-headset"></i>
          <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1" class="purecounter"></span>
          <p><%= t 'services_page.hours_of_support'%></p>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
        <div class="count-box">
          <i class="bi bi-people"></i>
          <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
          <p><%= t 'services_page.hard_workers'%></p>
        </div>
      </div>
    </div>
  </div>
</section><!-- End Counts Section -->

app/views/users/team.html.erb
<section id="team" class="team section-bg" style="margin-top: 50px">
    <div class="container">

        <div class="section-title">
            <h2><%= t 'team_page.team'%></h2>
            <p><%= t 'team_page.p_under_team'%></p>
        </div>

        <div class="row">
        <% @masters.each do |master|%>
            <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                <div class="member">
                    <div class="member-img">
                        <img src="/assets/theme/img/team/team-1.jpg" class="img-fluid" alt="">
                    </div>
                    <div class="member-info">
                        <h4><%= master.full_name%></h4>
                        <span> <%= master.phone_number %></span>
                    </div>
                </div>
            </div>
            <%end%>
        </div>
    </div>
</section>