config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "/#{I18n.locale}", controller: 'users', action: 'index'
  scope ':locale', locale: /ru|en/ do
    devise_for :users

    resources :clients, controller: :users, only: %i[index show] do
      resources :visits
    end

    resources :users, only: %i[destroy edit update]

    post '/search', to: 'search#search'
    get '/admin_index', to: 'visits#admin_index'
    get '/clients_list', to: 'users#clients'
    get '/team', to: 'users#team'
    put '/change_status', to: 'visits#change_status'
    get '/services', to: 'users#services'
    get '/portfolio', to: 'users#portfolio'
    get '*path', to: 'errors#error_404', via: :all
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# frozen_string_literal: true

class Client < User
  include Elasticsearch::Model
  
  has_many :visits, dependent: :destroy
  has_many :masters, through: :visits
end

app/models/master.rb
# frozen_string_literal: true
require 'elasticsearch/model'

class Master < User
  include Elasticsearch::Model

  has_many :visits
  has_many :users, through: :visits

  has_many :master_services
  has_many :services, through: :master_services

  accepts_nested_attributes_for :master_services

  validate :any_skills

  def any_skills
    errors.add(:services, "can't be blank") unless master_services.any?
  end
end

Master.__elasticsearch__.create_index!
Master.import

app/models/master_service.rb
# frozen_string_literal: true

class MasterService < ApplicationRecord
  belongs_to :master
  belongs_to :service
end

app/models/service.rb
# frozen_string_literal: true
require 'elasticsearch/model'

class Service < ApplicationRecord
  include Elasticsearch::Model
  
  has_many :service_visits, dependent: :destroy
  has_many :visits, through: :service_visits

  has_many :master_services, dependent: :destroy
  has_many :masters, through: :master_services

  monetize :price_cents

  validates_uniqueness_of :service_name

  validate :not_negative_price, :empty_service_name

  def not_negative_price
    errors.add(:price, "shouldn't be negative") if price.negative?
  end

  def empty_service_name
    errors.add(:service_name, "shoundn't be empty") if service_name == ''
  end
end

Service.__elasticsearch__.create_index!
Service.import

app/models/service_visit.rb
# frozen_string_literal: true

class ServiceVisit < ApplicationRecord
  belongs_to :service
  belongs_to :visit
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def full_name
    "#{first_name} #{last_name}"
  end

  validate :first_name_cannot_be_blank, :last_name_cannot_be_blank, :phone_number_cannot_be_blank, :email_cannot_be_blank

  def first_name_cannot_be_blank
    errors.add(:first_name, "shouldn't be empty") if first_name.blank?
  end

  def last_name_cannot_be_blank
    errors.add(:last_name, "shouldn't be empty") if last_name.blank?
  end

  def phone_number_cannot_be_blank
    errors.add(:phone_number, "shouldn't be empty") if phone_number.blank?
  end

  def email_cannot_be_blank
    errors.add(:email, "shouldn't be empty") if email.blank?
  end
end

app/models/visit.rb
# frozen_string_literal: true

class Visit < ApplicationRecord
  include AASM

  aasm column: 'state' do
    state :sent, initial: true
    state :confirmed
    state :done

    event :accepted do
      transitions from: :sent, to: :confirmed
    end

    event :finished do
      transitions from: :confirmed, to: :done
    end
  end

  belongs_to :client
  belongs_to :master

  has_one :service_visit, dependent: :destroy
  has_one :service, through: :service_visit

  accepts_nested_attributes_for :service_visit

  validate :master_should_to_support_service, :date_cannot_be_in_the_past

  def master_should_to_support_service
    errors.add(:service, "isn't supported by selected master") unless master.services.include?(service_visit.service)
  end

  def date_cannot_be_in_the_past
    errors.add(:date, 'must be in future') if date < Time.now
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  def error_404
    render 'errors/not_found'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @search_list = Elasticsearch::Model.search(params[:text], [Master, Service]).records.to_a
    respond_to do |format|
      format.js
      format.html { redirect_to root_path }
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController  
  def index
    @user = current_user
    @users = User.all
  end

  def destroy
    @user = find_user
    return redirect_to :users unless @user

    if current_user.is_a?(Admin) || current_user == @user
      reset_session if current_user == @user
      @user.destroy
      redirect_to :user
    end
  end

  def edit
    @user = current_user
    redirect_to users_path unless @user == current_user || current_user.is_a?(Admin)
  end

  def update
    @user = find_user
    if @user.update user_params
      redirect_to :root
    else
      render :edit
    end
  end

  def team
    @masters = Master.all
  end

  def services
    @services = Service.all
  end

  def clients
    @clients = User.all
  end

  private

  def user_params
    @required_key = @user.is_a?(Admin) ? :admin : :client
    params.require(@required_key).permit(:first_name, :last_name, :email, :phone_number)
  end

  def find_user
    User.find(params[:id])
  end
end

app/controllers/visits_controller.rb
# frozen_string_literal: true

class VisitsController < ApplicationController
  def index
    @client = current_user
    @visits = current_user.visits
  end

  def admin_index
    @all_visits = Visit.all
  end

  def change_status
    @visit = Visit.find(params[:visit_id])
    case @visit.state
    when 'sent'
      @visit.accepted!
    when 'confirmed'
      @visit.finished!
    end
    redirect_to admin_index_path
  end

  def new
    @client = current_user
    @masters = Master.all
    @services = Service.all
  end

  def create
    @visit = current_user.visits.build(visit_params)
    if @visit.valid?
      @visit.save
      redirect_to client_visits_path(current_user)
    else
      redirect_to new_client_visit_path(current_user), flash: { errors: @visit.errors.full_messages }
    end
  end

  def edit
    @client = current_user
    @visit = Visit.find_by(id: params[:id])
    redirect_to client_visits_path(current_user), notice: 'Redaction is possible only when state is sent' if @visit.state != 'sent'
  end

  def update
    @client = Client.find_by(id: params[:client_id])
    @visit = Visit.find_by(id: params[:id])
    @visit.update(visit_params)

    redirect_to client_visits_path(@client)
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    if current_user.is_a?(Admin)
      redirect_to admin_index_path
    else
      redirect_to client_visits_path(current_user)
    end
  end

  private

  def visit_params
    params.require(:visit).permit(:date, :addition, :master_id, service_visit_attributes: :service_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/confirmations_helper.rb
# frozen_string_literal: true

module ConfirmationsHelper
end

app/helpers/error_helper.rb
# frozen_string_literal: true

module ErrorHelper
end

app/helpers/errors_helper.rb
# frozen_string_literal: true

module ErrorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/visits_helper.rb
# frozen_string_literal: true

module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saloon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title id="title">Resi Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/assets/theme/img/favicon.png" rel="icon">
    <link href="/assets/theme/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/assets/theme/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/assets/theme/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/assets/theme/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/assets/theme/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Resi - v4.3.0
    * Template URL: https://bootstrapmade.com/resi-free-bootstrap-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header id="header" class="fixed-top ">
      <div class="container d-flex align-items-center justify-content-between">
        <h1><%= link_to t("header.SALON"), root_path, method: :get, class: 'nav-link scrollto '%></h1>
        <nav id="navbar" class="navbar">
          <ul>             
            <% if current_user%>
              <li>
                <%= form_with url: search_path, local: false, model: @text do |form| %>

                  <div class="form-floating">         
                    <%= form.text_field :text, class: 'form-control', id: 'text', required: true %>
                    <%= form.label 'Search', for: 'text' %>
                    <%= form.submit 'Searh', id: 'search_button', hidden: true %>
                  </div>
                <% end %>  

                <div id='results' style='position: relative; z-index: 2;'></div>   
              </li>
              <li class="dropdown"><a href="#"><span><%= t "header.visits_drop"%></span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                  <%unless current_user.is_a?(Admin)%>
                    <li><%= link_to t("header.add_visit"), new_client_visit_path(current_user), method: :get, class: 'nav-link scrollto ' %></li>
                  <%end%>
                  <%if current_user.is_a?(Admin)%>
                    <li><%= link_to t("header.all_visits"), admin_index_path(), method: :get, class: 'nav-link scrollto ' %></li>
                    <li><%= link_to t("header.clients_list"), clients_list_path(), method: :get, class: 'nav-link scrollto ' %></li>
                  <%else%>
                    <li><%= link_to t("header.my_visits"), client_visits_path(current_user), method: :get, class: 'nav-link scrollto ' %></li>
                  <%end%>
                </ul>
              </li>
            <%end%>
            <li><%= link_to t("header.services"), services_path, method: :get, class: 'nav-link scrollto '%></li>
            <li><%= link_to t("header.portfolio"), portfolio_path, method: :get, class: 'nav-link scrollto '%></li>
            <li><%= link_to t("header.team"), team_path, method: :get, class: 'nav-link scrollto '%></li>
            <% if current_user%>
              <li class="dropdown"><a href="#"><span><%= t "header.account_drop"%></span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                  <li><%= link_to t("header.sign_out"), destroy_user_session_path, method: :delete, class: 'nav-link scrollto' %></li>
                  <li><%= link_to t("header.edit"), edit_user_path(current_user), method: :get, class: 'nav-link scrollto' %></li>
                  <li><%= link_to t("header.delete"), user_path(current_user), method: :delete, data: { confirm: "Are you sure?" }, class: 'nav-link scrollto' %></li>
                  <a href=<%= url_for(locale: I18n.locale == :en ? :ru : :en)%>><%= t("header.lang") %></a>
                </ul>
              </li>
            <%end%>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
      </div>
    </header>
    <div id="flash" class="flash-container">
      <!-- flash notifications -->    
      <% flash.each do |type, msg| %>
        <%if type == "notice" %>
          <div class='alert alert-primary' role='alert'>
            <%= msg %>
          </div>
        <% end %> 

        <%if type == "errors" %>
          <% msg.each do |error|%>
            <div class='alert alert-warning' role='alert'>
              <%= error %>
            </div>  
          <%end%>          
        <% end %>
         
      <% end %> 
    </div>
    <!-- End flash notifications --> 
    <%= yield%>
  </body>
</html>

<script>
  $('#text').on('input', () =>
  {
    $('#search_button').click()
  })
</script>